FLOOR_HEIGHT_MIN_M = 2.3
FLOOR_HEIGHT_MAX_M = 4.6
COMFORT_HEIGHT_MIN_M = 2.8
COMFORT_HEIGHT_MAX_M = 3.6
DEFAULT_FLOOR_HEIGHT_M = 3.0

MAX_FLOORS = 8
MAX_BUILDING_HEIGHT_M = 24.0

SETBACK_STEP_M = 0.1
DEFAULT_SETBACK_M = 3.0

MIN_FLOOR_AREA_RATIO = 0.5
MIN_BUILDING_AREA_M2 = 20.0

GOLDEN_RATIO = 1.618
